[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "Hi"
description = "Hi"
version = "1.0"
[tool.poetry.dependencies]
flask = "1.1.1"
python = "^3.8"
textblob = "^0.15.3"
tweepy = "^3.8"
